# Generated by Django 6.0.2 on 2026-02-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrowdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]